### ISSUE TITLE
Stacking Layer causes error in AirPro

### ISSUE THREAD

**Issue by dulguunb** [CSi-Studio/AirdPro#2]
Hi, I read your paper: https://www.nature.com/articles/s41598-022-09432-1 and tried to replicate what was in the figure by giving the stack numbers but AirPro threw an error. I got this error below:

![remmina_Quick Connect_10 157 98 49_20240228-092400](https://github.com/CSi-Studio/AirdPro/assets/22801337/ad44468e-0815-48f1-b6ac-3c15a23c89a5)

I tried all of the files mentioned in the table of the paper: https://www.nature.com/articles/s41598-022-09432-1/tables/1

can you point out what I am doing wrong here?

**Comment by lumiaoshan** [comment]
Sorry for the bad experience. Since our newly developed algorithm framework has a better compression rate than stackZDPD algorithm, the StackZDPD code is no longer maintained, but as a compression algorithm, we have retained its implementation as StackCompressionUtil class in JavaSDK.
